# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
