# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='FOSS_Analysis.Project'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='FOSS_Analysis.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='FOSS_Analysis.Contributor'),
        ),
    ]
