# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blame',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='login',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='owner',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set([('login', 'email')]),
        ),
    ]
