# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0002_auto_20160319_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lines', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='contributor',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='FOSS_Analysis.Contributor'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='login',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blame',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='FOSS_Analysis.Contributor'),
        ),
        migrations.AddField(
            model_name='blame',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='FOSS_Analysis.File'),
        ),
    ]
