# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0003_auto_20160530_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
