# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0004_auto_20160530_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
