# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0005_auto_20160515_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blame',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blame',
            name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='copyrights',
        ),
        migrations.RemoveField(
            model_name='file',
            name='licenses',
        ),
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Blame',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Copyright',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
