# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FOSS_Analysis', '0006_auto_20160515_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lines', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('login', models.CharField(max_length=128, null=True, unique=True)),
                ('email', models.EmailField(max_length=128, null=True, unique=True)),
                ('type', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128, unique=True)),
                ('language', models.CharField(max_length=128, null=True)),
                ('copyrights', models.ManyToManyField(related_name='copyrights', to='FOSS_Analysis.Copyright')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('owner', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('contributors', models.ManyToManyField(related_name='contributors', to='FOSS_Analysis.Contributor')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='FOSS_Analysis.Contributor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together=set([('name', 'owner')]),
        ),
        migrations.AddField(
            model_name='file',
            name='licenses',
            field=models.ManyToManyField(related_name='licenses', to='FOSS_Analysis.License'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='FOSS_Analysis.Project'),
        ),
        migrations.AddField(
            model_name='blame',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='FOSS_Analysis.Contributor'),
        ),
        migrations.AddField(
            model_name='blame',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='FOSS_Analysis.File'),
        ),
    ]
