# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOSS_Analysis', '0007_auto_20160515_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='id',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='login',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
